import {utils} from '../utils.js'

export const TownNoBridgeMap = {
    id: "TownNoBridgeMap",
    lowerSrc: "/img/cartes/TownNoBridgeMap.png",
    upperSrc: "/img/cartes/TownNoBridgeMapUpper.png",
    configObjects: {
        hero: {
            type: "Person",
            src: "/img/personnages/personnes/me.png",
            isPlayerControlled: true,
            x: utils.withGrid(32),
            y: utils.withGrid(33),
            direction: "down",
            useShadow: true
        },
        npcA_School: {
            type: "Person",
            x: utils.withGrid(23),
            y: utils.withGrid(33),
            src: "/img/personnages/personnes/erio.png",
            behaviorLoop: [
                {type: "stand", direction: "left", time: 2200},
                {type: "stand", direction: "up", time: 1800},
                {type: "stand", direction: "right", time: 800},
                {type: "stand", direction: "up", time: 1200},
            ],
        },
        npcA_Bridge: {
            type: "Person",
            x: utils.withGrid(27),
            y: utils.withGrid(23),
            src: "/img/personnages/personnes/npc1.png",
            direction: "right",
            talking: [
                {
                    required: ["FIRST_AGENT_CHAT_1"],
                    events: [
                        { type: "textMessage", text: "Re-bonjour Monsieur ! Désolée, le pont est encore fermé. Veuillez accepter mes plus plates excuses...", who: "Agent Kool"},
                    ]
                },
                {
                    events: [
                        { type: "textMessage", text: "Le pont est fermé très cher Monsieur, peut-être pourriez-vous revenir plus tard ?", who: "Agent Kool"},
                        { type: "textMessage", text: "Excellente journée Monsieur !", who: "Agent Kool"},
                        { type: "addStoryFlag", flag: "FIRST_AGENT_CHAT_1"},
                    ]
                },
            ]
        },
        npcB_Bridge: {
            type: "Person",
            x: utils.withGrid(27),
            y: utils.withGrid(15),
            src: "/img/personnages/personnes/npc1.png",
            direction: "right",
            talking: [
                {
                    required: ["SECOND_AGENT_CHAT_1"],
                    events: [
                        { type: "textMessage", text: "T'as trois secondes pour dégager. Après ça, je te fais manger l'anus par les oreilles.", who: "Agent Kill"},
                    ]
                },
                {
                    events: [
                        { type: "textMessage", text: "Casse-toi c'est fermé !", who: "Agent Kill"},
                        { type: "textMessage", text: "Arrête de me regarder comme ça, je te défonce ! Taille la route casse noisette !", who: "Agent Kill"},
                        { type: "addStoryFlag", flag: "SECOND_AGENT_CHAT_1"},
                    ]
                },
            ]
        },


    },

    cutsceneSpaces: {
        [utils.asGridCoord(32,31)] : [
            {
                events: [
                    {
                        type: "changeMap",
                        map: "HeroHouseMap",
                        x: utils.withGrid(10),
                        y: utils.withGrid(11),
                        direction: "up"
                    },
                ],
            }
        ],
        [utils.asGridCoord(35,4)]: [
            {
                events: [
                    {
                        type: "changeMap",
                        map: "DemoRoom",
                        x: utils.withGrid(7),
                        y: utils.withGrid(7),
                        direction: "up"
                    },
                ]
            }
        ]
    },

    walls: {
        //Building Yellow swing
        [utils.asGridCoord(1, 2)]: true,
        [utils.asGridCoord(2, 2)]: true,
        [utils.asGridCoord(1, 3)]: true,
        [utils.asGridCoord(2, 3)]: true,

        //Building Yellow parking wall
        [utils.asGridCoord(0, 5)]: true,
        [utils.asGridCoord(1, 5)]: true,
        [utils.asGridCoord(2, 5)]: true,

        //Building Yellow tree
        [utils.asGridCoord(9, 6)]: true,
        [utils.asGridCoord(9, 7)]: true,

        //Building Yellow
        [utils.asGridCoord(4, 1)]: true,
        [utils.asGridCoord(5, 1)]: true,
        [utils.asGridCoord(6, 1)]: true,
        [utils.asGridCoord(7, 1)]: true,
        [utils.asGridCoord(7, 2)]: true,
        [utils.asGridCoord(7, 3)]: true,
        [utils.asGridCoord(7, 4)]: true,
        [utils.asGridCoord(7, 5)]: true,
        [utils.asGridCoord(7, 6)]: true,
        [utils.asGridCoord(7, 7)]: true,
        [utils.asGridCoord(7, 8)]: true,
        [utils.asGridCoord(4, 2)]: true,
        [utils.asGridCoord(4, 3)]: true,
        [utils.asGridCoord(4, 4)]: true,
        [utils.asGridCoord(4, 5)]: true,
        [utils.asGridCoord(4, 6)]: true,
        [utils.asGridCoord(4, 7)]: true,
        [utils.asGridCoord(4, 8)]: true,
        [utils.asGridCoord(5, 8)]: true,
        [utils.asGridCoord(6, 8)]: true,

        //House salmon between yellow building and mall
        [utils.asGridCoord(1, 17)]: true,
        [utils.asGridCoord(2, 17)]: true,
        [utils.asGridCoord(3, 17)]: true,
        [utils.asGridCoord(4, 17)]: true,
        [utils.asGridCoord(1, 16)]: true,
        [utils.asGridCoord(4, 16)]: true,
        [utils.asGridCoord(1, 15)]: true,
        [utils.asGridCoord(4, 15)]: true,
        [utils.asGridCoord(1, 14)]: true,
        [utils.asGridCoord(2, 14)]: true,
        [utils.asGridCoord(3, 14)]: true,
        [utils.asGridCoord(4, 14)]: true,

        //House blue between yellow building and mall
        [utils.asGridCoord(6, 15)]: true,
        [utils.asGridCoord(7, 15)]: true,
        [utils.asGridCoord(8, 15)]: true,
        [utils.asGridCoord(9, 15)]: true,
        [utils.asGridCoord(6, 12)]: true,
        [utils.asGridCoord(6, 13)]: true,
        [utils.asGridCoord(6, 14)]: true,
        [utils.asGridCoord(7, 12)]: true,
        [utils.asGridCoord(6, 12)]: true,
        [utils.asGridCoord(8, 12)]: true,
        [utils.asGridCoord(9, 12)]: true,
        [utils.asGridCoord(9, 13)]: true,
        [utils.asGridCoord(9, 14)]: true,
        [utils.asGridCoord(7, 16)]: true,

        //Mall
        [utils.asGridCoord(0, 23)]: true,
        [utils.asGridCoord(1, 23)]: true,
        [utils.asGridCoord(2, 23)]: true,
        [utils.asGridCoord(3, 23)]: true,
        [utils.asGridCoord(4, 23)]: true,
        [utils.asGridCoord(4, 24)]: true,
        [utils.asGridCoord(5, 24)]: true,
        [utils.asGridCoord(6, 24)]: true,
        [utils.asGridCoord(7, 24)]: true,
        [utils.asGridCoord(8, 24)]: true,
        [utils.asGridCoord(9, 24)]: true,
        [utils.asGridCoord(10, 24)]: true,
        [utils.asGridCoord(10, 25)]: true,
        [utils.asGridCoord(8, 26)]: true,
        [utils.asGridCoord(10, 26)]: true,
        [utils.asGridCoord(10, 27)]: true,
        [utils.asGridCoord(10, 28)]: true,
        [utils.asGridCoord(7, 27)]: true,
        [utils.asGridCoord(7, 28)]: true,
        [utils.asGridCoord(9, 27)]: true,
        [utils.asGridCoord(9, 28)]: true,
        [utils.asGridCoord(10, 29)]: true,
        [utils.asGridCoord(9, 29)]: true,
        [utils.asGridCoord(7, 29)]: true,
        [utils.asGridCoord(6, 29)]: true,
        [utils.asGridCoord(5, 29)]: true,
        [utils.asGridCoord(4, 29)]: true,
        [utils.asGridCoord(3, 29)]: true,
        [utils.asGridCoord(2, 29)]: true,
        [utils.asGridCoord(1, 29)]: true,
        [utils.asGridCoord(0, 29)]: true,

        //Mall decoration
        [utils.asGridCoord(7, 31)]: true,
        [utils.asGridCoord(7, 32)]: true,
        [utils.asGridCoord(7, 35)]: true,
        [utils.asGridCoord(7, 36)]: true,
        [utils.asGridCoord(0, 33)]: true,
        [utils.asGridCoord(0, 34)]: true,

        //University
        [utils.asGridCoord(12, 3)]: true,
        [utils.asGridCoord(12, 4)]: true,
        [utils.asGridCoord(12, 5)]: true,
        [utils.asGridCoord(12, 6)]: true,
        [utils.asGridCoord(12, 7)]: true,
        [utils.asGridCoord(12, 8)]: true,
        [utils.asGridCoord(14, 8)]: true,
        [utils.asGridCoord(16, 8)]: true,
        [utils.asGridCoord(12, 9)]: true,
        [utils.asGridCoord(18, 9)]: true,
        [utils.asGridCoord(17, 9)]: true,
        [utils.asGridCoord(16, 9)]: true,
        [utils.asGridCoord(13, 9)]: true,
        [utils.asGridCoord(14, 9)]: true,
        [utils.asGridCoord(13, 3)]: true,
        [utils.asGridCoord(14, 3)]: true,
        [utils.asGridCoord(14, 7)]: true,
        [utils.asGridCoord(15, 3)]: true,
        [utils.asGridCoord(15, 5)]: true,
        [utils.asGridCoord(15, 6)]: true,
        [utils.asGridCoord(16, 3)]: true,
        [utils.asGridCoord(16, 7)]: true,
        [utils.asGridCoord(17, 3)]: true,
        [utils.asGridCoord(18, 3)]: true,
        [utils.asGridCoord(19, 3)]: true,
        [utils.asGridCoord(20, 3)]: true,
        [utils.asGridCoord(21, 3)]: true,
        [utils.asGridCoord(22, 3)]: true,
        [utils.asGridCoord(23, 4)]: true,
        [utils.asGridCoord(23, 5)]: true,
        [utils.asGridCoord(23, 6)]: true,
        [utils.asGridCoord(23, 7)]: true,
        [utils.asGridCoord(23, 8)]: true,
        [utils.asGridCoord(22, 8)]: true,
        [utils.asGridCoord(21, 8)]: true,
        [utils.asGridCoord(20, 8)]: true,
        [utils.asGridCoord(19, 8)]: true,

        //University decoration and tree
        [utils.asGridCoord(12, 10)]: true,
        [utils.asGridCoord(12, 11)]: true,
        [utils.asGridCoord(12, 13)]: true,
        [utils.asGridCoord(13, 13)]: true,
        [utils.asGridCoord(20, 12)]: true,
        [utils.asGridCoord(20, 13)]: true,
        [utils.asGridCoord(23, 13)]: true,
        [utils.asGridCoord(23, 12)]: true,
        [utils.asGridCoord(23, 11)]: true,
        [utils.asGridCoord(24, 13)]: true,
        [utils.asGridCoord(24, 12)]: true,
        [utils.asGridCoord(24, 11)]: true,
        [utils.asGridCoord(22, 10)]: true,
        [utils.asGridCoord(18, 11)]: true,

        //Bridge top
        [utils.asGridCoord(25, 14)]: true,
        [utils.asGridCoord(25, 16)]: true,
        [utils.asGridCoord(26, 16)]: true,
        [utils.asGridCoord(27, 16)]: true,
        [utils.asGridCoord(28, 16)]: true,
        [utils.asGridCoord(26, 14)]: true,
        [utils.asGridCoord(27, 14)]: true,
        [utils.asGridCoord(28, 14)]: true,

        //Bridge top piller
        [utils.asGridCoord(24, 16)]: true,
        [utils.asGridCoord(24, 17)]: true,
        [utils.asGridCoord(24, 18)]: true,
        [utils.asGridCoord(24, 19)]: true,
        [utils.asGridCoord(24, 20)]: true,
        [utils.asGridCoord(24, 21)]: true,
        [utils.asGridCoord(24, 22)]: true,
        [utils.asGridCoord(28, 17)]: true,
        [utils.asGridCoord(28, 18)]: true,
        [utils.asGridCoord(28, 19)]: true,
        [utils.asGridCoord(28, 20)]: true,
        [utils.asGridCoord(28, 21)]: true,
        [utils.asGridCoord(28, 22)]: true,

        //Bridge top decoration
        [utils.asGridCoord(29, 14)]: true,
        [utils.asGridCoord(30, 14)]: true,


        //Bridge bottom
        [utils.asGridCoord(25, 22)]: true,
        [utils.asGridCoord(26, 22)]: true,
        [utils.asGridCoord(27, 22)]: true,
        [utils.asGridCoord(25, 24)]: true,
        [utils.asGridCoord(26, 24)]: true,
        [utils.asGridCoord(27, 24)]: true,
        [utils.asGridCoord(28, 24)]: true,

        //Bridge bottom piller
        [utils.asGridCoord(24, 24)]: true,
        [utils.asGridCoord(24, 25)]: true,
        [utils.asGridCoord(24, 26)]: true,
        [utils.asGridCoord(24, 27)]: true,
        [utils.asGridCoord(24, 28)]: true,
        [utils.asGridCoord(24, 29)]: true,
        [utils.asGridCoord(28, 25)]: true,
        [utils.asGridCoord(28, 26)]: true,
        [utils.asGridCoord(28, 27)]: true,
        [utils.asGridCoord(28, 28)]: true,

        //Fountain
        [utils.asGridCoord(16, 16)]: true,
        [utils.asGridCoord(17, 16)]: true,
        [utils.asGridCoord(18, 16)]: true,
        [utils.asGridCoord(19, 16)]: true,
        [utils.asGridCoord(20, 16)]: true,
        [utils.asGridCoord(16, 17)]: true,
        [utils.asGridCoord(16, 18)]: true,
        [utils.asGridCoord(16, 19)]: true,
        [utils.asGridCoord(17, 19)]: true,
        [utils.asGridCoord(18, 19)]: true,
        [utils.asGridCoord(19, 19)]: true,
        [utils.asGridCoord(20, 19)]: true,
        [utils.asGridCoord(20, 17)]: true,
        [utils.asGridCoord(20, 18)]: true,

        //Fountain decoration
        [utils.asGridCoord(17, 21)]: true,
        [utils.asGridCoord(18, 21)]: true,
        [utils.asGridCoord(19, 21)]: true,
        [utils.asGridCoord(17, 22)]: true,
        [utils.asGridCoord(18, 22)]: true,
        [utils.asGridCoord(19, 22)]: true,
        [utils.asGridCoord(13, 17)]: true,
        [utils.asGridCoord(13, 18)]: true,
        [utils.asGridCoord(13, 19)]: true,
        [utils.asGridCoord(14, 17)]: true,
        [utils.asGridCoord(14, 18)]: true,
        [utils.asGridCoord(14, 19)]: true,

        //School
        [utils.asGridCoord(15, 30)]: true,
        [utils.asGridCoord(17, 30)]: true,
        [utils.asGridCoord(18, 30)]: true,
        [utils.asGridCoord(19, 30)]: true,
        [utils.asGridCoord(21, 30)]: true,
        [utils.asGridCoord(15, 27)]: true,
        [utils.asGridCoord(15, 28)]: true,
        [utils.asGridCoord(15, 29)]: true,
        [utils.asGridCoord(16, 27)]: true,
        [utils.asGridCoord(16, 27)]: true,
        [utils.asGridCoord(16, 28)]: true,
        [utils.asGridCoord(17, 27)]: true,
        [utils.asGridCoord(18, 27)]: true,
        [utils.asGridCoord(19, 27)]: true,
        [utils.asGridCoord(20, 27)]: true,
        [utils.asGridCoord(20, 28)]: true,
        [utils.asGridCoord(21, 27)]: true,
        [utils.asGridCoord(21, 28)]: true,
        [utils.asGridCoord(21, 29)]: true,
        [utils.asGridCoord(17, 29)]: true,
        [utils.asGridCoord(19, 29)]: true,

        //School fence
        [utils.asGridCoord(22, 30)]: true,
        [utils.asGridCoord(23, 30)]: true,
        [utils.asGridCoord(24, 35)]: true,
        [utils.asGridCoord(23, 35)]: true,
        [utils.asGridCoord(22, 35)]: true,
        [utils.asGridCoord(21, 35)]: true,
        [utils.asGridCoord(20, 35)]: true,
        [utils.asGridCoord(19, 35)]: true,
        [utils.asGridCoord(17, 35)]: true,
        [utils.asGridCoord(12, 35)]: true,
        [utils.asGridCoord(13, 35)]: true,
        [utils.asGridCoord(14, 35)]: true,
        [utils.asGridCoord(15, 35)]: true,
        [utils.asGridCoord(16, 35)]: true,
        [utils.asGridCoord(12, 34)]: true,
        [utils.asGridCoord(12, 33)]: true,
        [utils.asGridCoord(12, 32)]: true,
        [utils.asGridCoord(12, 31)]: true,
        [utils.asGridCoord(12, 30)]: true,
        [utils.asGridCoord(13, 30)]: true,
        [utils.asGridCoord(14, 30)]: true,

        //School decoration and tree
        [utils.asGridCoord(13, 38)]: true,
        [utils.asGridCoord(13, 27)]: true,
        [utils.asGridCoord(21, 38)]: true,
        [utils.asGridCoord(22, 39)]: true,
        [utils.asGridCoord(24, 39)]: true,
        [utils.asGridCoord(24, 38)]: true,

        //Restaurant next to company
        [utils.asGridCoord(29, 4)]: true,
        [utils.asGridCoord(29, 3)]: true,
        [utils.asGridCoord(29, 2)]: true,
        [utils.asGridCoord(29, 1)]: true,
        [utils.asGridCoord(30, 0)]: true,
        [utils.asGridCoord(31, 0)]: true,
        [utils.asGridCoord(32, 0)]: true,
        [utils.asGridCoord(30, 4)]: true,
        [utils.asGridCoord(31, 4)]: true,
        [utils.asGridCoord(32, 4)]: true,
        [utils.asGridCoord(33, 4)]: true,

        //Company
        [utils.asGridCoord(34, 4)]: true,
        [utils.asGridCoord(34, 5)]: true,
        [utils.asGridCoord(35, 3)]: true,
        [utils.asGridCoord(36, 4)]: true,
        [utils.asGridCoord(36, 5)]: true,
        [utils.asGridCoord(37, 5)]: true,
        [utils.asGridCoord(38, 5)]: true,
        [utils.asGridCoord(39, 5)]: true,

        //Company decoration
        [utils.asGridCoord(31, 10)]: true,
        [utils.asGridCoord(32, 10)]: true,
        [utils.asGridCoord(36, 8)]: true,
        [utils.asGridCoord(36, 9)]: true,
        [utils.asGridCoord(36, 10)]: true,
        [utils.asGridCoord(37, 8)]: true,
        [utils.asGridCoord(37, 9)]: true,
        [utils.asGridCoord(37, 10)]: true,
        [utils.asGridCoord(32, 7)]: true,

        //Building blue parking
        [utils.asGridCoord(31, 18)]: true,
        [utils.asGridCoord(32, 18)]: true,
        [utils.asGridCoord(33, 18)]: true,
        [utils.asGridCoord(34, 18)]: true,

        //Building blue
        [utils.asGridCoord(35, 17)]: true,
        [utils.asGridCoord(35, 18)]: true,
        [utils.asGridCoord(35, 19)]: true,
        [utils.asGridCoord(35, 20)]: true,
        [utils.asGridCoord(35, 21)]: true,
        [utils.asGridCoord(35, 22)]: true,
        [utils.asGridCoord(36, 17)]: true,
        [utils.asGridCoord(37, 17)]: true,
        [utils.asGridCoord(38, 17)]: true,
        [utils.asGridCoord(38, 18)]: true,
        [utils.asGridCoord(38, 19)]: true,
        [utils.asGridCoord(38, 20)]: true,
        [utils.asGridCoord(38, 21)]: true,
        [utils.asGridCoord(38, 22)]: true,
        [utils.asGridCoord(36, 22)]: true,
        [utils.asGridCoord(37, 22)]: true,

        //Home
        [utils.asGridCoord(31, 29)]: true,
        [utils.asGridCoord(31, 30)]: true,
        [utils.asGridCoord(31, 31)]: true,
        [utils.asGridCoord(31, 32)]: true,
        [utils.asGridCoord(33, 31)]: true,
        [utils.asGridCoord(33, 32)]: true,
        [utils.asGridCoord(32, 29)]: true,
        [utils.asGridCoord(33, 29)]: true,
        [utils.asGridCoord(33, 30)]: true,
        [utils.asGridCoord(34, 29)]: true,
        [utils.asGridCoord(34, 32)]: true,
        [utils.asGridCoord(35, 33)]: true,
        [utils.asGridCoord(36, 33)]: true,
        [utils.asGridCoord(37, 33)]: true,
        [utils.asGridCoord(38, 33)]: true,
        [utils.asGridCoord(37, 30)]: true,
        [utils.asGridCoord(36, 30)]: true,
        [utils.asGridCoord(35, 30)]: true,
        [utils.asGridCoord(38, 30)]: true,
        [utils.asGridCoord(38, 31)]: true,
        [utils.asGridCoord(38, 32)]: true,

        //Home decoration and tree
        [utils.asGridCoord(32, 26)]: true,
        [utils.asGridCoord(33, 26)]: true,
        [utils.asGridCoord(34, 26)]: true,
        [utils.asGridCoord(37, 26)]: true,
        [utils.asGridCoord(33, 35)]: true,
        [utils.asGridCoord(34, 35)]: true,
        [utils.asGridCoord(37, 35)]: true,

        //WATER BORDER LEFT
        [utils.asGridCoord(25, 0)]: true,
        [utils.asGridCoord(25, 1)]: true,
        [utils.asGridCoord(25, 2)]: true,
        [utils.asGridCoord(25, 3)]: true,
        [utils.asGridCoord(25, 4)]: true,
        [utils.asGridCoord(25, 5)]: true,
        [utils.asGridCoord(25, 6)]: true,
        [utils.asGridCoord(25, 7)]: true,
        [utils.asGridCoord(25, 8)]: true,
        [utils.asGridCoord(25, 9)]: true,
        [utils.asGridCoord(25, 10)]: true,
        [utils.asGridCoord(25, 11)]: true,
        [utils.asGridCoord(25, 12)]: true,
        [utils.asGridCoord(25, 13)]: true,
        [utils.asGridCoord(25, 30)]: true,
        [utils.asGridCoord(25, 31)]: true,
        [utils.asGridCoord(25, 32)]: true,
        [utils.asGridCoord(25, 33)]: true,
        [utils.asGridCoord(25, 34)]: true,
        [utils.asGridCoord(25, 35)]: true,
        [utils.asGridCoord(25, 36)]: true,
        [utils.asGridCoord(25, 37)]: true,
        [utils.asGridCoord(25, 38)]: true,
        [utils.asGridCoord(25, 39)]: true,

        //WATER BORDER RIGHT
        [utils.asGridCoord(27, 0)]: true,
        [utils.asGridCoord(27, 1)]: true,
        [utils.asGridCoord(27, 2)]: true,
        [utils.asGridCoord(27, 3)]: true,
        [utils.asGridCoord(27, 4)]: true,
        [utils.asGridCoord(27, 5)]: true,
        [utils.asGridCoord(27, 6)]: true,
        [utils.asGridCoord(27, 7)]: true,
        [utils.asGridCoord(27, 8)]: true,
        [utils.asGridCoord(27, 9)]: true,
        [utils.asGridCoord(27, 10)]: true,
        [utils.asGridCoord(27, 11)]: true,
        [utils.asGridCoord(27, 12)]: true,
        [utils.asGridCoord(27, 13)]: true,
        [utils.asGridCoord(27, 29)]: true,
        [utils.asGridCoord(27, 30)]: true,
        [utils.asGridCoord(27, 31)]: true,
        [utils.asGridCoord(27, 32)]: true,
        [utils.asGridCoord(27, 33)]: true,
        [utils.asGridCoord(27, 34)]: true,
        [utils.asGridCoord(27, 35)]: true,
        [utils.asGridCoord(27, 36)]: true,
        [utils.asGridCoord(27, 37)]: true,
        [utils.asGridCoord(27, 38)]: true,
        [utils.asGridCoord(27, 39)]: true,

        //MAP BORDER TOP
        [utils.asGridCoord(0, -1)]: true,
        [utils.asGridCoord(1, -1)]: true,
        [utils.asGridCoord(2, -1)]: true,
        [utils.asGridCoord(3, -1)]: true,
        [utils.asGridCoord(4, -1)]: true,
        [utils.asGridCoord(5, -1)]: true,
        [utils.asGridCoord(6, -1)]: true,
        [utils.asGridCoord(7, -1)]: true,
        [utils.asGridCoord(8, -1)]: true,
        [utils.asGridCoord(9, -1)]: true,
        [utils.asGridCoord(10, -1)]: true,
        [utils.asGridCoord(11, -1)]: true,
        [utils.asGridCoord(12, -1)]: true,
        [utils.asGridCoord(13, -1)]: true,
        [utils.asGridCoord(14, -1)]: true,
        [utils.asGridCoord(15, -1)]: true,
        [utils.asGridCoord(16, -1)]: true,
        [utils.asGridCoord(17, -1)]: true,
        [utils.asGridCoord(18, -1)]: true,
        [utils.asGridCoord(19, -1)]: true,
        [utils.asGridCoord(20, -1)]: true,
        [utils.asGridCoord(21, -1)]: true,
        [utils.asGridCoord(22, -1)]: true,
        [utils.asGridCoord(23, -1)]: true,
        [utils.asGridCoord(24, -1)]: true,
        [utils.asGridCoord(25, -1)]: true,
        [utils.asGridCoord(26, -1)]: true,
        [utils.asGridCoord(27, -1)]: true,
        [utils.asGridCoord(28, -1)]: true,
        [utils.asGridCoord(29, -1)]: true,
        [utils.asGridCoord(30, -1)]: true,
        [utils.asGridCoord(31, -1)]: true,
        [utils.asGridCoord(32, -1)]: true,
        [utils.asGridCoord(33, -1)]: true,
        [utils.asGridCoord(34, -1)]: true,
        [utils.asGridCoord(35, -1)]: true,
        [utils.asGridCoord(36, -1)]: true,
        [utils.asGridCoord(37, -1)]: true,
        [utils.asGridCoord(38, -1)]: true,
        [utils.asGridCoord(39, -1)]: true,

        //MAP BORDER LEFT
        [utils.asGridCoord(-1, 0)]: true,
        [utils.asGridCoord(-1, 1)]: true,
        [utils.asGridCoord(-1, 2)]: true,
        [utils.asGridCoord(-1, 3)]: true,
        [utils.asGridCoord(-1, 4)]: true,
        [utils.asGridCoord(-1, 5)]: true,
        [utils.asGridCoord(-1, 6)]: true,
        [utils.asGridCoord(-1, 7)]: true,
        [utils.asGridCoord(-1, 8)]: true,
        [utils.asGridCoord(-1, 9)]: true,
        [utils.asGridCoord(-1, 10)]: true,
        [utils.asGridCoord(-1, 11)]: true,
        [utils.asGridCoord(-1, 12)]: true,
        [utils.asGridCoord(-1, 13)]: true,
        [utils.asGridCoord(-1, 14)]: true,
        [utils.asGridCoord(-1, 15)]: true,
        [utils.asGridCoord(-1, 16)]: true,
        [utils.asGridCoord(-1, 17)]: true,
        [utils.asGridCoord(-1, 18)]: true,
        [utils.asGridCoord(-1, 19)]: true,
        [utils.asGridCoord(-1, 20)]: true,
        [utils.asGridCoord(-1, 21)]: true,
        [utils.asGridCoord(-1, 22)]: true,
        [utils.asGridCoord(-1, 29)]: true,
        [utils.asGridCoord(-1, 30)]: true,
        [utils.asGridCoord(-1, 31)]: true,
        [utils.asGridCoord(-1, 32)]: true,
        [utils.asGridCoord(-1, 35)]: true,
        [utils.asGridCoord(-1, 36)]: true,
        [utils.asGridCoord(-1, 37)]: true,
        [utils.asGridCoord(-1, 38)]: true,
        [utils.asGridCoord(-1, 39)]: true,

        //MAP BORDER BOTTOM
        [utils.asGridCoord(0, 40)]: true,
        [utils.asGridCoord(1, 40)]: true,
        [utils.asGridCoord(2, 40)]: true,
        [utils.asGridCoord(3, 40)]: true,
        [utils.asGridCoord(4, 40)]: true,
        [utils.asGridCoord(5, 40)]: true,
        [utils.asGridCoord(6, 40)]: true,
        [utils.asGridCoord(7, 40)]: true,
        [utils.asGridCoord(8, 40)]: true,
        [utils.asGridCoord(9, 40)]: true,
        [utils.asGridCoord(10, 40)]: true,
        [utils.asGridCoord(11, 40)]: true,
        [utils.asGridCoord(12, 40)]: true,
        [utils.asGridCoord(13, 40)]: true,
        [utils.asGridCoord(14, 40)]: true,
        [utils.asGridCoord(15, 40)]: true,
        [utils.asGridCoord(16, 40)]: true,
        [utils.asGridCoord(17, 40)]: true,
        [utils.asGridCoord(18, 40)]: true,
        [utils.asGridCoord(19, 40)]: true,
        [utils.asGridCoord(20, 40)]: true,
        [utils.asGridCoord(21, 40)]: true,
        [utils.asGridCoord(22, 40)]: true,
        [utils.asGridCoord(23, 40)]: true,
        [utils.asGridCoord(24, 40)]: true,
        [utils.asGridCoord(25, 40)]: true,
        [utils.asGridCoord(26, 40)]: true,
        [utils.asGridCoord(27, 40)]: true,
        [utils.asGridCoord(28, 40)]: true,
        [utils.asGridCoord(29, 40)]: true,
        [utils.asGridCoord(30, 40)]: true,
        [utils.asGridCoord(31, 40)]: true,
        [utils.asGridCoord(32, 40)]: true,
        [utils.asGridCoord(33, 40)]: true,
        [utils.asGridCoord(34, 40)]: true,
        [utils.asGridCoord(35, 40)]: true,
        [utils.asGridCoord(36, 40)]: true,
        [utils.asGridCoord(37, 40)]: true,
        [utils.asGridCoord(38, 40)]: true,
        [utils.asGridCoord(39, 40)]: true,

        //MAP BORDER RIGHT
        [utils.asGridCoord(40, 6)]: true,
        [utils.asGridCoord(40, 7)]: true,
        [utils.asGridCoord(40, 8)]: true,
        [utils.asGridCoord(40, 9)]: true,
        [utils.asGridCoord(40, 10)]: true,
        [utils.asGridCoord(40, 11)]: true,
        [utils.asGridCoord(40, 12)]: true,
        [utils.asGridCoord(40, 13)]: true,
        [utils.asGridCoord(40, 14)]: true,
        [utils.asGridCoord(40, 15)]: true,
        [utils.asGridCoord(40, 16)]: true,
        [utils.asGridCoord(40, 17)]: true,
        [utils.asGridCoord(40, 18)]: true,
        [utils.asGridCoord(40, 19)]: true,
        [utils.asGridCoord(40, 20)]: true,
        [utils.asGridCoord(40, 21)]: true,
        [utils.asGridCoord(40, 22)]: true,
        [utils.asGridCoord(40, 23)]: true,
        [utils.asGridCoord(40, 24)]: true,
        [utils.asGridCoord(40, 25)]: true,
        [utils.asGridCoord(40, 26)]: true,
        [utils.asGridCoord(40, 27)]: true,
        [utils.asGridCoord(40, 28)]: true,
        [utils.asGridCoord(40, 29)]: true,
        [utils.asGridCoord(40, 30)]: true,
        [utils.asGridCoord(40, 31)]: true,
        [utils.asGridCoord(40, 32)]: true,
        [utils.asGridCoord(40, 33)]: true,
        [utils.asGridCoord(40, 34)]: true,
        [utils.asGridCoord(40, 35)]: true,
        [utils.asGridCoord(40, 36)]: true,
        [utils.asGridCoord(40, 37)]: true,
        [utils.asGridCoord(40, 38)]: true,
        [utils.asGridCoord(40, 39)]: true,

    }
}